import {
  AlertTriangle,
  ArrowRight,
  Bell,
  BellOff,
  Building2,
  Check,
  ChevronDown,
  CircleCheck,
  CircleX,
  ClipboardCheck,
  Heart,
  Home,
  Info,
  LayoutDashboard,
  Link2,
  LogOut,
  MapPin,
  MessageCircle,
  Newspaper,
  Package,
  Plus,
  Search,
  ShoppingCart,
  Sprout,
  Star,
  Trash2,
  Truck,
  UserCircle,
  UserRound,
  WalletCards,
  Send,
  ZoomIn,
  X,
  Apple, Bird, Bug, Carrot, Dog, Droplet, Fish, Leaf, Rabbit, Sprout, Tractor, Wheat
} from "lucide-react";

const ICONS = {
  alert: AlertTriangle,
  arrowRight: ArrowRight,
  bell: Bell,
  bellOff: BellOff,
  building: Building2,
  check: Check,
  chevronDown: ChevronDown,
  checkCircle: CircleCheck,
  closeCircle: CircleX,
  clipboard: ClipboardCheck,
  heart: Heart,
  home: Home,
  info: Info,
  dashboard: LayoutDashboard,
  link: Link2,
  logout: LogOut,
  mapPin: MapPin,
  message: MessageCircle,
  newspaper: Newspaper,
  package: Package,
  plus: Plus,
  search: Search,
  cart: ShoppingCart,
  sprout: Sprout,
  star: Star,
  trash: Trash2,
  truck: Truck,
  user: UserRound,
  userCircle: UserCircle,
  wallet: WalletCards,
  send: Send,
  zoomIn: ZoomIn,
  close: X,
  apple: Apple,
  bird: Bird,
  bug: Bug,
  carrot: Carrot,
  dog: Dog,
  droplet: Droplet,
  fish: Fish,
  leaf: Leaf,
  rabbit: Rabbit,
  sprout: Sprout,
  tractor: Tractor,
  wheat: Wheat,
};

export default function Icon({ name, size = 18, strokeWidth = 1.8, className = "", ...props }) {
  const IconComponent = ICONS[name] || Info;
  return <IconComponent size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" {...props} />;
}
